Document: cpts
Title: Debian cpts Manual
Author: <insert document author here>
Abstract: This manual describes what cpts is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/cpts/cpts.sgml.gz

Format: postscript
Files: /usr/share/doc/cpts/cpts.ps.gz

Format: text
Files: /usr/share/doc/cpts/cpts.text.gz

Format: HTML
Index: /usr/share/doc/cpts/html/index.html
Files: /usr/share/doc/cpts/html/*.html
